---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.css"
  - "**.coffee"
  - "**.js"
  - "**.jsx"
exclude_paths:
  - config/**/*
  - db/**/*
  - script/**/*
  - spec/**/*
  - test/**/*
  - vendor/**/*
