AllCops:
  TargetRubyVersion: 2.2
  Exclude:
    - 'bin/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'Guardfile'
    - 'Rakefile'
Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
  Enabled: true
  Exclude:
    - 'config/**/*'
Rails/TimeZone:
  Enabled: false
SignalException:
  Enabled: false
Style/DotPosition:
  EnforcedStyle: leading
Style/PredicateName:
  NamePrefix:
    - is_
    - have_
  NamePrefixBlacklist:
    - is_
    - have_
Style/StringLiterals:
  EnforcedStyle: double_quotes
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
  Enabled: true
